In [2]:
import joblib
import pandas as pd

In [3]:
df = pd.read_csv('model/cleaned_data.csv')
example = pd.read_csv("model/required_data_format.csv")
example.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,bmi
0,43.778082,1,167.0,85.0,100.0,80.0,2,2,0,0,1,30.477966
1,52.013699,0,165.0,65.0,130.0,80.0,1,1,0,0,1,23.875115

In [4]:
model = joblib.load("model/gbc_model.pkl")

In [8]:
data = pd.DataFrame({
    'age': [37.6],
    'gender': [0],
    'height': [153],
    'weight': [46],
    'ap_hi': [110],
    'ap_lo': [80],
    'cholesterol': [2],
    'gluc': [1],
    'smoke': [0],
    'alco': [0],
    'active': [0],
    'bmi': [46/(153/100)**2]}
    )
data

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,bmi
0,37.6,0,153,46,110,80,2,1,0,0,0,19.650562

In [9]:
model.fit(df.drop(columns=['cardio']), df['cardio'])

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['age', 'height', 'weight',
                                                   'ap_hi', 'ap_lo', 'bmi']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['gender', 'cholesterol',
                                                   'gluc', 'smoke', 'alco',
                                                   'active'])],
                                   verbose_feature_names_out=False)),
                ('model',
                 GradientBoostingClassifier(max_leaf_nodes=16,
                                            random_state=42))])

In [10]:
model.predict_proba(data)

array([[0.90529291, 0.09470709]])